### ISSUE TITLE
would you please add README to show how to use it

### ISSUE THREAD

**Issue by leesf** [FJShen/sparktest#2]

**Comment by FJShen** [comment]
Coming soon! My Apologies for the inconvenience.

**Comment by leesf** [comment]
> Coming soon! My Apologies for the inconvenience.

Thanks.

**Comment by leesf** [comment]
@FJShen hi, any new updates here?

**Comment by FJShen** [comment]
A README file has been created. Please bear with the coarseness of this repo/readme file for a while, as I acknowledge there is much work to do to improve the universality of this project.

**Comment by leesf** [comment]
> A README file has been created. Please bear with the coarseness of this repo/readme file for a while, as I acknowledge there is much work to do to improve the universality of this project.

Thanks. Closing the issue.
